### ISSUE TITLE
short explanation of use

### ISSUE THREAD

**Issue by ppollet73** [TheFrozenFire/PHP-Swagger-Parser#1]
Hello,
I'm very interested in using your php swagger-parser, however i do not know how to start, could you please publish a short example ?

Thanks in advance

Pierre

**Comment by TheFrozenFire** [comment]
Hi Pierre,

This library is still in very active development, and although I'm confident that it's roughly stable at this point, I'd suggest considering other tools unless you need to do very fine-tuned parsing of Swagger JSON.

That being said, you should be able to load a resource listing by simply passing its JSON to a Swagger\ResourceListing in its constructor (e.g. new Swagger\ResourceListing($json) ). For individual API declarations, you can do the same, with the API declaration JSON as a parameter.

Beyond that, you should simply be able to call each getter to navigate through the hierarchy of the JSON.

Let me know if you're confused, or if there are specific features you need in the parser. By and large, I'm aiming to keep the library simple, so that it does nothing more than parse the JSON input, and allow you to spit the state back out into a JSON string.
